//! RV32IMC decoder/disassembler checked against `llvm-objdump` (riscv32imc) output for every
//! base and compressed encoding class with random and edge-case operands; see `vectors.rs`
//! (generated by `gen_vectors.py`, checked in).
//!
//! `RISCV_FULL=<file>` additionally checks an exhaustive local dump (`gen_vectors.py --full`:
//! every 16-bit encoding plus ~180k 32-bit words).

mod vectors;

use mcs_core::riscv::decode::{decode, insn_len, Op};
use mcs_core::riscv::disasm::{csr_name, disassemble, reg_name};
use vectors::VECTORS;

fn word_of(bytes: &[u8]) -> u32 {
    bytes.iter().enumerate().fold(0, |w, (k, &b)| w | (b as u32) << (8 * k))
}

fn check(addr: u32, bytes: &[u8], want: &str) -> Result<(), String> {
    let word = word_of(bytes);
    let (len, got) = disassemble(word, addr);
    if len as usize != bytes.len() {
        return Err(format!("{addr:#x}: {bytes:02x?} length {len}, objdump {}", bytes.len()));
    }
    if got != want {
        return Err(format!("{addr:#x}: {bytes:02x?} ours `{got}` objdump `{want}`"));
    }
    Ok(())
}

#[test]
fn disassembly_matches_llvm_objdump() {
    assert!(VECTORS.len() > 2000, "{} vectors", VECTORS.len());
    let errs: Vec<String> = VECTORS.iter().filter_map(|&(a, b, t)| check(a, b, t).err()).collect();
    assert!(errs.is_empty(), "{} mismatches, first: {:#?}", errs.len(), &errs[..errs.len().min(25)]);
}

#[test]
fn every_instruction_class_is_covered_by_the_vectors() {
    // Every mnemonic family of the supported ISA must appear in the vectors.
    let must = [
        "lui", "auipc", "jal", "jalr", "beq", "bne", "blt", "bge", "bltu", "bgeu", "lb", "lh", "lw", "lbu", "lhu", "sb", "sh", "sw", "addi", "slti",
        "sltiu", "xori", "ori", "andi", "slli", "srli", "srai", "add", "sub", "sll", "slt", "sltu", "xor", "srl", "sra", "or", "and", "mul",
        "mulh", "mulhsu", "mulhu", "div", "divu", "rem", "remu", "fence", "fence.i", "ecall", "ebreak", "mret", "wfi", "csrrw", "csrrs", "csrrc",
        "csrrwi", "csrrsi", "csrrci", "li", "mv", "j", "ret", "nop", "jr", "beqz", "bnez", "neg", "not", "seqz", "snez", "csrr", "csrw",
    ];
    for m in must {
        assert!(VECTORS.iter().any(|v| v.2.split(' ').next() == Some(m)), "no vector for `{m}`");
    }
    // Compressed vectors for each quadrant, and every compressed funct3 class decodes somewhere.
    let c16 = VECTORS.iter().filter(|v| v.1.len() == 2).count();
    let c32 = VECTORS.iter().filter(|v| v.1.len() == 4).count();
    assert!(c16 > 500 && c32 > 1000, "{c16} compressed / {c32} base vectors");
}

#[test]
fn lengths_and_shape() {
    assert_eq!(insn_len(0x4501), 2);
    assert_eq!(insn_len(0x0513), 4);
    assert_eq!(std::mem::size_of::<mcs_core::riscv::Insn>(), 12);
    // c.li a0, 0 -> addi a0, x0, 0 with length 2
    let i = decode(0x4501);
    assert_eq!((i.op, i.rd, i.rs1, i.imm, i.len), (Op::Addi, 10, 0, 0, 2));
    // 48-bit prefix and the all-zero halfword are illegal
    assert_eq!(decode(0x0000_001f).op, Op::Illegal);
    assert_eq!(decode(0).op, Op::Illegal);
    assert_eq!(decode(0x0000_0000).len, 2);
}

#[test]
fn names() {
    assert_eq!(reg_name(0), "zero");
    assert_eq!(reg_name(2), "sp");
    assert_eq!(reg_name(8), "s0");
    assert_eq!(reg_name(31), "t6");
    assert_eq!(csr_name(0x300), Some("mstatus"));
    assert_eq!(csr_name(0x305), Some("mtvec"));
    assert_eq!(csr_name(0xb00), Some("mcycle"));
    assert_eq!(csr_name(0x7c0), None);
}

#[test]
fn exhaustive_dump_if_available() {
    let Ok(path) = std::env::var("RISCV_FULL") else { return };
    let text = std::fs::read_to_string(path).expect("RISCV_FULL file");
    let mut errs = Vec::new();
    let mut n = 0;
    for line in text.lines() {
        let mut it = line.splitn(3, ' ');
        let addr = u32::from_str_radix(it.next().unwrap(), 16).unwrap();
        let hex = it.next().unwrap();
        let want = it.next().unwrap_or("");
        let bytes: Vec<u8> = (0..hex.len() / 2).map(|k| u8::from_str_radix(&hex[2 * k..2 * k + 2], 16).unwrap()).collect();
        n += 1;
        if let Err(e) = check(addr, &bytes, want) {
            errs.push(e);
        }
    }
    if let Ok(out) = std::env::var("RISCV_FULL_ERRS") {
        std::fs::write(out, errs.join("\n")).unwrap();
    }
    for e in errs.iter().take(20) {
        eprintln!("{e}");
    }
    assert!(errs.is_empty(), "{} of {n} mismatches", errs.len());
}
