//! Beginner usage help (what an instruction is for, how to use it, an example) for every
//! canonical AVR mnemonic and the common assembler aliases. Shown in editor hovers and the
//! Instruction Set panel. Source: Microchip "AVR Instruction Set Manual" (DS40002198B).

/// Usage help: when to use an instruction, its operand rules, and a short example.
#[derive(Clone, Copy, Debug)]
pub struct InsnUsage {
    /// 1-3 plain-English sentences: when/why you'd use it, operand rules, typical pitfalls.
    pub help: &'static str,
    /// A short assembly example (1-4 lines, '\n' separated, with `; comments`), avrasm2 syntax.
    pub example: &'static str,
}

const fn u(help: &'static str, example: &'static str) -> InsnUsage {
    InsnUsage { help, example }
}

/// Usage help for a canonical lower-case mnemonic (as in `isa_docs.rs`).
pub fn insn_usage(name: &str) -> Option<InsnUsage> {
    Some(match name {
        "adc" => u("Adds two registers plus the Carry flag. Use it after ADD to build 16/32-bit sums: add the low bytes with ADD, then the next bytes with ADC so the carry ripples upward.",
            "add r24, r22  ; low bytes\nadc r25, r23  ; high bytes + carry"),
        "add" => u("Adds register Rr to Rd and stores the result in Rd (8-bit). The C flag shows an unsigned overflow; use ADC for the next byte of a multi-byte add. There is no add-immediate: use SUBI with the negated value instead.",
            "ldi r16, 10\nldi r17, 5\nadd r16, r17  ; r16 = 15"),
        "adiw" => u("Adds a constant 0-63 to a register pair (16-bit). Rd must be R24, R26, R28 or R30 (the pairs R25:R24, X, Y, Z). Handy for stepping pointers or 16-bit counters.",
            "adiw r26, 4  ; X = X + 4\nadiw r24, 1  ; 16-bit counter++"),
        "and" => u("Bitwise AND of two registers into Rd. Use it to keep only chosen bits (a mask) or to test whether bits are set; the result is zero (Z flag) if none were.",
            "mov r16, r17\nand r16, r18  ; keep only bits set in both"),
        "andi" => u("Bitwise AND of a register with a constant. Rd must be R16-R31. Use it to clear bits: AND with a mask that has 0 in the bits you want to clear.",
            "andi r16, 0x0F  ; keep low nibble\nandi r17, ~(1<<3)  ; clear bit 3"),
        "asr" => u("Shifts a register right one bit but keeps the sign bit (bit 7), so it halves a signed (two's complement) number. The bit shifted out lands in Carry.",
            "ldi r16, 0xF8  ; -8\nasr r16        ; -4 (0xFC)"),
        "bclr" => u("Clears flag number s (0-7) in the status register SREG. Usually written with the named forms (CLC, CLZ, CLI ...), which read more clearly.",
            "bclr 0  ; same as CLC\nbclr 7  ; same as CLI"),
        "bld" => u("Copies the T flag into bit b of a register. Pair it with BST to move a single bit from one register/bit position to another.",
            "bst r16, 0  ; T = r16 bit 0\nbld r17, 7  ; r17 bit 7 = T"),
        "brbc" => u("Branches if flag number s in SREG is 0. Normally you use the named forms (BRNE, BRCC, BRPL ...). The target must be within -64..+63 words of the instruction; for farther targets branch over an RJMP/JMP.",
            "brbc 1, again  ; same as BRNE again"),
        "brbs" => u("Branches if flag number s in SREG is 1. Normally you use the named forms (BREQ, BRCS, BRMI ...). The target must be within -64..+63 words; for farther targets branch over an RJMP/JMP.",
            "brbs 1, done  ; same as BREQ done"),
        "break" => u("Stops the CPU when an on-chip debugger (debugWIRE/JTAG) is attached; otherwise it acts as a NOP. You rarely write it by hand.",
            "break  ; debugger stops here"),
        "bset" => u("Sets flag number s (0-7) in the status register SREG. Usually written with the named forms (SEC, SEZ, SEI ...).",
            "bset 7  ; same as SEI"),
        "bst" => u("Copies bit b of a register into the T flag. Use it to remember one bit, then BRTS/BRTC to branch on it or BLD to write it elsewhere.",
            "bst r16, 3  ; T = r16 bit 3\nbrts bit_was_set"),
        "call" => u("Calls a subroutine anywhere in program memory: pushes the return address and jumps. Finish the subroutine with RET. Needs the stack pointer to be initialised first; on devices with 8 KB or less flash RCALL is smaller and faster.",
            "call delay_ms  ; run subroutine\n; ...\ndelay_ms:\n  ret"),
        "cbi" => u("Clears one bit (0-7) of an I/O register without touching the others, e.g. to drive a pin low. Only works on low I/O addresses 0-31 (PORTx, DDRx, PINx on most chips).",
            "cbi PORTB, 0  ; PB0 low"),
        "com" => u("One's complement: flips every bit in the register (0xFF - Rd). Useful for inverting a bit pattern. It always sets Carry.",
            "ldi r16, 0x0F\ncom r16  ; r16 = 0xF0"),
        "cp" => u("Compares two registers by subtracting them, but throws the result away: only the flags change. Always follow it with a conditional branch. Use BREQ/BRNE for equality, BRLO/BRSH for unsigned, BRLT/BRGE for signed.",
            "cp r16, r17\nbrlo less  ; r16 < r17 (unsigned)"),
        "cpc" => u("Compare with Carry: like CP but also subtracts the carry from the previous compare. Chain CP on the low bytes then CPC on higher bytes to compare 16/32-bit numbers.",
            "cp r24, r22   ; low bytes\ncpc r25, r23  ; high bytes\nbrlo less16"),
        "cpi" => u("Compares a register with a constant (flags only, nothing stored). Rd must be R16-R31. Follow with a conditional branch.",
            "cpi r16, 10\nbreq is_ten"),
        "cpse" => u("Compares two registers and skips the next instruction if they are equal. A quick way to guard one instruction; the skipped instruction can be 1 or 2 words (e.g. CALL) and the CPU handles both.",
            "cpse r16, r17\nrjmp not_equal  ; skipped when equal"),
        "dec" => u("Subtracts 1 from a register. Does not change Carry. Classic loop counter: DEC then BRNE repeats until the register reaches zero.",
            "ldi r16, 8\nloop:\n  dec r16\n  brne loop  ; runs 8 times"),
        "des" => u("Performs one round of the DES encryption algorithm on R0-R15. Only available on XMEGA devices. K selects the round and encrypt/decrypt.",
            "des 0  ; round 0, encrypt"),
        "eicall" => u("Calls a subroutine at the address EIND:Z. Only on devices with more than 128 KB of flash. Set EIND and Z first.",
            "ldi r30, low(func)\nldi r31, high(func)\neicall"),
        "eijmp" => u("Jumps to the address EIND:Z. Only on devices with more than 128 KB of flash. Useful for jump tables.",
            "eijmp  ; PC = EIND:Z"),
        "elpm" => u("Reads a byte of flash from the 24-bit address RAMPZ:Z (flash beyond 64 KB). Z holds a BYTE address (word address x 2). Use ELPM Rd, Z+ to auto-increment through a table.",
            "ldi r30, low(table*2)\nldi r31, high(table*2)\nelpm r16, Z+"),
        "eor" => u("Bitwise exclusive OR. Flips the bits that are 1 in the second register. EOR Rd,Rd clears a register to zero (written CLR).",
            "eor r16, r17  ; toggle bits set in r17\neor r18, r18  ; r18 = 0"),
        "fmul" => u("Unsigned fractional multiply: multiplies two 1.7 fixed-point numbers into a 1.15 result in R1:R0. For DSP-style fixed point maths. Rd and Rr must be R16-R23. Needs a device with a hardware multiplier.",
            "fmul r16, r17  ; R1:R0 = (r16*r17) << 1"),
        "fmuls" => u("Signed fractional multiply of two 1.7 fixed-point numbers; result in R1:R0 as 1.15. Rd and Rr must be R16-R23. Needs a device with a hardware multiplier.",
            "fmuls r16, r17"),
        "fmulsu" => u("Fractional multiply of a signed Rd by an unsigned Rr; result in R1:R0. Rd and Rr must be R16-R23. Needs a device with a hardware multiplier.",
            "fmulsu r16, r17"),
        "icall" => u("Calls the subroutine whose word address is in the Z register (R31:R30). Useful for function pointers. Return with RET.",
            "ldi r30, low(func)\nldi r31, high(func)\nicall"),
        "ijmp" => u("Jumps to the word address in Z (R31:R30). Useful for jump tables and state machines.",
            "ldi r30, low(state)\nldi r31, high(state)\nijmp"),
        "in" => u("Reads an I/O register into a CPU register, e.g. to read pins or a status register. For I/O addresses above 0x3F (extended I/O) use LDS instead.",
            "in r16, PINB  ; read pin states\nin r17, SREG  ; read flags"),
        "inc" => u("Adds 1 to a register without changing Carry. Handy as a counter; the register wraps from 0xFF to 0.",
            "inc r16\ncpi r16, 10\nbrne again"),
        "jmp" => u("Jumps to any address in program memory (4-byte instruction). Use RJMP when the target is within +-2K words since it is smaller and faster. Only on devices with more than 8 KB flash.",
            "jmp main"),
        "lac" => u("Atomically clears in memory the bits that are set in Rd: (Z) <- (Z) AND NOT Rd, and returns the old value in Rd. XMEGA only. Safe to use with interrupts.",
            "ldi r16, 0x01\nlac Z, r16  ; clear bit 0 at (Z)"),
        "las" => u("Atomically sets in memory the bits that are set in Rd: (Z) <- (Z) OR Rd, returning the old value in Rd. XMEGA only.",
            "ldi r16, 0x01\nlas Z, r16  ; set bit 0 at (Z)"),
        "lat" => u("Atomically toggles in memory the bits that are set in Rd: (Z) <- (Z) XOR Rd, returning the old value in Rd. XMEGA only.",
            "ldi r16, 0x01\nlat Z, r16  ; toggle bit 0 at (Z)"),
        "ld" => u("Loads a byte from data memory (RAM or I/O) at the address held in X, Y or Z. Add + after the pointer to increment it afterwards, or - before to decrement it first. Useful for walking through arrays and buffers.",
            "ldi r26, low(buf)\nldi r27, high(buf)\nld r16, X+  ; read, then X++"),
        "ldd" => u("Loads a byte from data memory at Y or Z plus a small offset q (0-63) without changing the pointer. Good for struct fields and stack-frame variables.",
            "ldd r16, Y+2  ; read byte at Y+2\nldd r17, Z+0"),
        "ldi" => u("Loads a constant (0-255) into a register. Rd must be R16-R31; R0-R15 cannot take immediates. Use it to set up values before OUT, calculations, or loops.",
            "ldi r16, 0xFF\nout DDRB, r16  ; all PORTB pins outputs"),
        "lds" => u("Loads a byte from a fixed data-memory address (RAM variable or extended I/O register). 2 words, 2 cycles.",
            "lds r16, counter  ; read RAM variable\nlds r17, UDR0"),
        "lpm" => u("Reads a byte from flash (program memory) at the BYTE address in Z, e.g. constant tables and strings. Multiply a label's word address by 2 to get the byte address. LPM Rd, Z+ auto-increments Z.",
            "ldi r30, low(msg*2)\nldi r31, high(msg*2)\nlpm r16, Z+  ; first char"),
        "lsr" => u("Shifts a register right one bit, filling bit 7 with 0. The same as dividing an unsigned number by 2; the bit shifted out goes to Carry.",
            "lsr r16  ; r16 = r16 / 2"),
        "mov" => u("Copies one register into another; the source is unchanged. Works on all registers R0-R31. For a 16-bit pair use MOVW.",
            "mov r17, r16  ; r17 = r16"),
        "movw" => u("Copies a register pair to another pair in one instruction. Both operands must be even-numbered registers (r0, r2, ... r30); each names the low register of its pair.",
            "movw r30, r24  ; Z (r31:r30) = r25:r24"),
        "mul" => u("Unsigned 8x8 multiply; the 16-bit result goes in R1:R0 (R1 is high). Needs a device with a hardware multiplier (most ATmega). Note: avr-gcc expects R1 to be 0 afterwards.",
            "ldi r16, 20\nldi r17, 30\nmul r16, r17  ; R1:R0 = 600"),
        "muls" => u("Signed 8x8 multiply with a 16-bit result in R1:R0. Both registers must be R16-R31. Needs a hardware multiplier.",
            "muls r16, r17  ; signed r16*r17"),
        "mulsu" => u("Multiplies a signed register by an unsigned register; 16-bit result in R1:R0. Both registers must be R16-R23.",
            "mulsu r16, r17  ; signed*unsigned"),
        "neg" => u("Two's complement negation: Rd = 0 - Rd. Turns a positive number into its negative equivalent and vice versa.",
            "ldi r16, 5\nneg r16  ; r16 = -5 (0xFB)"),
        "nop" => u("Does nothing for one clock cycle. Use for tiny delays or to pad timing, e.g. waiting a cycle for a synchronizer between writing and reading a pin.",
            "out PORTB, r16\nnop  ; allow the pin to settle\nin r17, PINB"),
        "or" => u("Bitwise OR of two registers into Rd. Use it to set bits or to combine flag values.",
            "or r16, r17  ; set bits that are set in r17"),
        "ori" => u("Bitwise OR of a register with a constant. Rd must be R16-R31. Use it to set bits without disturbing the rest.",
            "ori r16, (1<<2)|(1<<5)  ; set bits 2 and 5"),
        "out" => u("Writes a CPU register to an I/O register: set pin directions, drive outputs, configure peripherals. For I/O addresses above 0x3F use STS instead.",
            "ldi r16, 0xFF\nout DDRB, r16  ; outputs\nout PORTB, r16  ; drive high"),
        "pop" => u("Takes the top byte off the stack into a register (and increments SP). Pop in the opposite order to your pushes.",
            "push r16\n; ... r16 reused\npop r16  ; restored"),
        "push" => u("Stores a register on the stack (then decrements SP). Use it to save registers at the start of an interrupt handler or subroutine, then POP them in reverse order. SP must be initialised first.",
            "push r16\nin r16, SREG\npush r16"),
        "rcall" => u("Calls a subroutine within +-2K words of this instruction: pushes the return address and jumps. Smaller and faster than CALL. End the subroutine with RET. Set up the stack pointer first.",
            "rcall delay\n; ...\ndelay:\n  ret"),
        "ret" => u("Returns from a subroutine: pops the return address into the program counter. Must match a CALL/RCALL; an unbalanced PUSH/POP will make it return to the wrong place.",
            "my_func:\n  inc r16\n  ret"),
        "reti" => u("Returns from an interrupt handler and re-enables global interrupts (sets the I flag). Use it at the end of every ISR instead of RET.",
            "TIMER0_OVF_ISR:\n  inc r20\n  reti"),
        "rjmp" => u("Jumps to a label within +-2K words (+-4 KB) of this instruction. Used for loops and main-loop jumps. For farther targets use JMP (on devices that have it).",
            "main_loop:\n  sbi PINB, 0  ; toggle LED\n  rjmp main_loop"),
        "ror" => u("Rotates a register right through Carry: Carry goes into bit 7 and bit 0 goes to Carry. Use it after LSR to shift multi-byte numbers right.",
            "lsr r25  ; 16-bit >> 1\nror r24"),
        "sbc" => u("Subtract with Carry: Rd = Rd - Rr - C. Use after SUB to subtract multi-byte numbers (C carries the borrow). Z is only kept cleared, so a multi-byte zero test works.",
            "sub r24, r22  ; low bytes\nsbc r25, r23  ; high bytes"),
        "sbci" => u("Subtracts a constant and the Carry flag from a register. Rd must be R16-R31. Use after SUBI for multi-byte subtraction (or adding a negated constant).",
            "subi r24, low(1000)\nsbci r25, high(1000)  ; 16-bit - 1000"),
        "sbi" => u("Sets one bit (0-7) of an I/O register without touching the others, e.g. to drive a pin high. Only works on low I/O addresses 0-31. On newer chips writing 1 to PINx toggles the pin.",
            "sbi DDRB, 0   ; PB0 output\nsbi PORTB, 0  ; PB0 high"),
        "sbic" => u("Skips the next instruction if a bit in an I/O register is 0. Great for polling: wait for a pin or flag. Works on I/O addresses 0-31 only.",
            "sbic PINB, 2\nrjmp pin_is_high  ; skipped if PB2 = 0"),
        "sbis" => u("Skips the next instruction if a bit in an I/O register is 1. Typical use: busy-wait for a flag, e.g. loop until a peripheral sets its done bit. I/O addresses 0-31 only.",
            "wait:\n  sbis TIFR0, TOV0  ; skip when overflow flag set\n  rjmp wait"),
        "sbiw" => u("Subtracts a constant 0-63 from a register pair (16-bit). Rd must be R24, R26, R28 or R30. A tidy 16-bit down-counter: SBIW then BRNE.",
            "ldi r24, low(1000)\nldi r25, high(1000)\nloop:\n  sbiw r24, 1\n  brne loop"),
        "sbrc" => u("Skips the next instruction if bit b of a register is 0. Lets you test a single bit without a compare.",
            "sbrc r16, 7\nrjmp negative  ; skipped when bit 7 is 0"),
        "sbrs" => u("Skips the next instruction if bit b of a register is 1.",
            "sbrs r16, 0\nrjmp even  ; skipped when bit 0 is 1"),
        "sleep" => u("Puts the CPU into the sleep mode chosen in SMCR (set SE first) to save power; an interrupt wakes it. Enable interrupts before sleeping or it may never wake.",
            "ldi r16, (1<<SE)\nout SMCR, r16\nsei\nsleep"),
        "spm" => u("Self-programming: writes the flash page buffer using R1:R0 and Z. Only usable from the bootloader section on devices that support it, with a strict timing sequence.",
            "spm  ; see device datasheet"),
        "st" => u("Stores a register to data memory (RAM or I/O) at the address in X, Y or Z. Add + after the pointer to increment it afterwards, or - before to decrement it first. Good for filling buffers.",
            "ldi r26, low(buf)\nldi r27, high(buf)\nst X+, r16  ; write, then X++"),
        "std" => u("Stores a register to data memory at Y or Z plus a small offset q (0-63), without changing the pointer.",
            "std Y+2, r16  ; write byte at Y+2"),
        "sts" => u("Stores a register to a fixed data-memory address (RAM variable or extended I/O register). 2 words, 2 cycles.",
            "sts counter, r16\nsts UDR0, r17"),
        "sub" => u("Subtracts register Rr from Rd without carry. After it, C is set if Rd < Rr unsigned (a borrow). For multi-byte subtraction use SBC on the next bytes.",
            "sub r16, r17  ; r16 = r16 - r17"),
        "subi" => u("Subtracts a constant from a register. Rd must be R16-R31. There is no ADDI: add a constant by subtracting its negative, e.g. SUBI r16, -5. Use SBCI for higher bytes.",
            "subi r16, 1    ; decrement\nsubi r17, -10  ; r17 += 10"),
        "swap" => u("Exchanges the high and low 4-bit halves of a register. Handy for packed BCD digits or nibble access.",
            "ldi r16, 0x3A\nswap r16  ; r16 = 0xA3"),
        "wdr" => u("Resets (kicks) the watchdog timer so it does not reset the chip. Call it regularly from the main loop if the watchdog is enabled, more often than its timeout.",
            "main_loop:\n  wdr\n  rjmp main_loop"),
        "xch" => u("Atomically swaps register Rd with the data-memory byte at Z. XMEGA only.",
            "xch Z, r16"),
        _ => return None,
    })
}

/// An assembler alias that encodes as another instruction.
#[derive(Clone, Copy, Debug)]
pub struct Alias {
    pub name: &'static str,
    /// Canonical lower-case mnemonic this alias encodes as.
    pub of: &'static str,
    pub operands: &'static str,
    pub summary: &'static str,
    pub operation: &'static str,
    pub usage: InsnUsage,
}

const fn al(
    name: &'static str,
    of: &'static str,
    operands: &'static str,
    summary: &'static str,
    operation: &'static str,
    usage: InsnUsage,
) -> Alias {
    Alias { name, of, operands, summary, operation, usage }
}


pub const ALIASES: &[Alias] = &[
    // --- BRBS / BRBC ---
    al("breq", "brbs", "k", "Branch if Equal", "if Z = 1 then PC <- PC + k + 1",
        u("Branches if the Zero flag is set, i.e. the last compare/arithmetic result was zero (values equal). Use after CP/CPI/SUB/DEC. Target must be within -64..+63 words.",
          "cpi r16, 5\nbreq is_five")),
    al("brne", "brbc", "k", "Branch if Not Equal", "if Z = 0 then PC <- PC + k + 1",
        u("Branches if the Zero flag is clear, i.e. the last result was not zero (values differ). The usual loop-back branch after DEC. Target must be within -64..+63 words.",
          "ldi r16, 10\nagain:\n  dec r16\n  brne again")),
    al("brcs", "brbs", "k", "Branch if Carry Set", "if C = 1 then PC <- PC + k + 1",
        u("Branches if Carry is set. After a compare this means unsigned Rd < Rr (same as BRLO). Target must be within -64..+63 words.",
          "cp r16, r17\nbrcs r16_smaller")),
    al("brcc", "brbc", "k", "Branch if Carry Cleared", "if C = 0 then PC <- PC + k + 1",
        u("Branches if Carry is clear. After a compare this means unsigned Rd >= Rr (same as BRSH). Target must be within -64..+63 words.",
          "cpi r16, 100\nbrcc at_least_100")),
    al("brsh", "brbc", "k", "Branch if Same or Higher (unsigned)", "if C = 0 then PC <- PC + k + 1",
        u("Unsigned >= after a compare (identical to BRCC). For signed numbers use BRGE instead. Target must be within -64..+63 words.",
          "cp r16, r17\nbrsh r16_ge_r17  ; unsigned")),
    al("brlo", "brbs", "k", "Branch if Lower (unsigned)", "if C = 1 then PC <- PC + k + 1",
        u("Unsigned < after a compare (identical to BRCS). For signed numbers use BRLT instead. Target must be within -64..+63 words.",
          "cpi r16, 10\nbrlo below_ten  ; unsigned")),
    al("brmi", "brbs", "k", "Branch if Minus", "if N = 1 then PC <- PC + k + 1",
        u("Branches if the Negative flag is set (bit 7 of the result is 1), e.g. a negative signed result. Target must be within -64..+63 words.",
          "subi r16, 5\nbrmi went_negative")),
    al("brpl", "brbc", "k", "Branch if Plus", "if N = 0 then PC <- PC + k + 1",
        u("Branches if the Negative flag is clear (result is 0 or positive). Target must be within -64..+63 words.",
          "dec r16\nbrpl keep_going  ; loop while r16 >= 0")),
    al("brge", "brbc", "k", "Branch if Greater or Equal (signed)", "if S = 0 then PC <- PC + k + 1",
        u("Signed >= after a compare. For unsigned numbers use BRSH instead. Target must be within -64..+63 words.",
          "cp r16, r17\nbrge r16_ge_r17  ; signed")),
    al("brlt", "brbs", "k", "Branch if Less Than (signed)", "if S = 1 then PC <- PC + k + 1",
        u("Signed < after a compare. For unsigned numbers use BRLO instead. Target must be within -64..+63 words.",
          "cpi r16, 0\nbrlt negative  ; signed")),
    al("brhs", "brbs", "k", "Branch if Half Carry Set", "if H = 1 then PC <- PC + k + 1",
        u("Branches if the half-carry flag (carry out of bit 3) is set. Used in BCD arithmetic. Target must be within -64..+63 words.",
          "add r16, r17\nbrhs bcd_adjust")),
    al("brhc", "brbc", "k", "Branch if Half Carry Cleared", "if H = 0 then PC <- PC + k + 1",
        u("Branches if the half-carry flag is clear. Used in BCD arithmetic. Target must be within -64..+63 words.",
          "add r16, r17\nbrhc no_adjust")),
    al("brts", "brbs", "k", "Branch if T Flag Set", "if T = 1 then PC <- PC + k + 1",
        u("Branches if the T flag is set. T is a one-bit scratch flag, loaded with BST. Target must be within -64..+63 words.",
          "bst r16, 3\nbrts bit3_set")),
    al("brtc", "brbc", "k", "Branch if T Flag Cleared", "if T = 0 then PC <- PC + k + 1",
        u("Branches if the T flag is clear. T is a one-bit scratch flag, loaded with BST. Target must be within -64..+63 words.",
          "bst r16, 3\nbrtc bit3_clear")),
    al("brvs", "brbs", "k", "Branch if Overflow Flag Set", "if V = 1 then PC <- PC + k + 1",
        u("Branches if the signed overflow flag is set (a signed result did not fit in 8 bits). Target must be within -64..+63 words.",
          "add r16, r17\nbrvs overflow")),
    al("brvc", "brbc", "k", "Branch if Overflow Flag Cleared", "if V = 0 then PC <- PC + k + 1",
        u("Branches if the signed overflow flag is clear (the signed result is valid). Target must be within -64..+63 words.",
          "add r16, r17\nbrvc no_overflow")),
    al("brie", "brbs", "k", "Branch if Interrupt Enabled", "if I = 1 then PC <- PC + k + 1",
        u("Branches if global interrupts are enabled (I flag set). Target must be within -64..+63 words.",
          "brie ints_on")),
    al("brid", "brbc", "k", "Branch if Interrupt Disabled", "if I = 0 then PC <- PC + k + 1",
        u("Branches if global interrupts are disabled (I flag clear). Target must be within -64..+63 words.",
          "brid ints_off")),
    // --- BSET / BCLR ---
    al("sec", "bset", "", "Set Carry Flag", "C <- 1",
        u("Sets the Carry flag. Use before ROR/ROL/ADC/SBC when you need a known carry-in.", "sec\nror r16  ; bit 7 = 1")),
    al("clc", "bclr", "", "Clear Carry Flag", "C <- 0",
        u("Clears the Carry flag. Use before ADC/ROL/ROR when you need a known carry-in of 0.", "clc\nrol r16  ; bit 0 = 0")),
    al("sez", "bset", "", "Set Zero Flag", "Z <- 1",
        u("Sets the Zero flag.", "sez")),
    al("clz", "bclr", "", "Clear Zero Flag", "Z <- 0",
        u("Clears the Zero flag.", "clz")),
    al("sen", "bset", "", "Set Negative Flag", "N <- 1",
        u("Sets the Negative flag.", "sen")),
    al("cln", "bclr", "", "Clear Negative Flag", "N <- 0",
        u("Clears the Negative flag.", "cln")),
    al("sev", "bset", "", "Set Overflow Flag", "V <- 1",
        u("Sets the signed Overflow flag.", "sev")),
    al("clv", "bclr", "", "Clear Overflow Flag", "V <- 0",
        u("Clears the signed Overflow flag.", "clv")),
    al("ses", "bset", "", "Set Signed Flag", "S <- 1",
        u("Sets the Sign flag (N xor V).", "ses")),
    al("cls", "bclr", "", "Clear Signed Flag", "S <- 0",
        u("Clears the Sign flag (N xor V).", "cls")),
    al("seh", "bset", "", "Set Half Carry Flag", "H <- 1",
        u("Sets the Half-carry flag.", "seh")),
    al("clh", "bclr", "", "Clear Half Carry Flag", "H <- 0",
        u("Clears the Half-carry flag.", "clh")),
    al("set", "bset", "", "Set T Flag", "T <- 1",
        u("Sets the T flag, a one-bit scratch flag used with BST/BLD/BRTS/BRTC.", "set\nbld r16, 0  ; r16 bit 0 = 1")),
    al("clt", "bclr", "", "Clear T Flag", "T <- 0",
        u("Clears the T flag, a one-bit scratch flag used with BST/BLD/BRTS/BRTC.", "clt\nbld r16, 0  ; r16 bit 0 = 0")),
    al("sei", "bset", "", "Set Global Interrupt Flag", "I <- 1",
        u("Enables interrupts globally. Call it once your interrupt vectors and the stack are set up. The instruction after SEI always executes before any pending interrupt is taken, so SEI followed by SLEEP is safe.",
          "sei  ; interrupts on")),
    al("cli", "bclr", "", "Clear Global Interrupt Flag", "I <- 0",
        u("Disables interrupts globally. Use it around short critical sections (e.g. reading a 16-bit value an ISR changes), then SEI again; or save/restore SREG to keep the earlier state.",
          "cli\nlds r16, count16\nlds r17, count16+1\nsei")),
    // --- register aliases ---
    al("lsl", "add", "Rd", "Logical Shift Left", "Rd <- Rd << 1, C <- Rd(7)",
        u("Shifts a register left one bit, filling bit 0 with 0; same as multiplying an unsigned number by 2. The old bit 7 goes to Carry. Assembled as ADD Rd,Rd. Follow with ROL for multi-byte shifts.",
          "lsl r24  ; 16-bit << 1\nrol r25")),
    al("rol", "adc", "Rd", "Rotate Left through Carry", "Rd <- Rd << 1 | C, C <- Rd(7)",
        u("Rotates a register left through Carry: Carry enters bit 0 and bit 7 goes to Carry. Assembled as ADC Rd,Rd. Use after LSL to shift multi-byte numbers left.",
          "lsl r24\nrol r25  ; 16-bit << 1")),
    al("tst", "and", "Rd", "Test for Zero or Minus", "Rd & Rd (flags only)",
        u("Sets the Z and N flags according to a register without changing it. Assembled as AND Rd,Rd. Follow it with BREQ/BRNE (zero) or BRMI/BRPL (negative).",
          "tst r16\nbreq was_zero")),
    al("clr", "eor", "Rd", "Clear Register", "Rd <- Rd ^ Rd = 0",
        u("Sets a register to 0. Assembled as EOR Rd,Rd, so it also sets Z and clears N, V, S. Works on any register R0-R31 (unlike LDI).",
          "clr r1  ; r1 = 0")),
    al("ser", "ldi", "Rd", "Set Register", "Rd <- 0xFF",
        u("Sets every bit of a register to 1 (0xFF). Assembled as LDI Rd,0xFF so Rd must be R16-R31. Handy for setting a whole port as outputs.",
          "ser r16\nout DDRB, r16  ; all outputs")),
    al("cbr", "andi", "Rd, K", "Clear Bits in Register", "Rd <- Rd & (0xFF - K)",
        u("Clears the bits that are 1 in K. Assembled as ANDI Rd,~K, so Rd must be R16-R31. ANDI with the inverted mask does the same.",
          "cbr r16, 0x81  ; clear bits 7 and 0")),
    al("sbr", "ori", "Rd, K", "Set Bits in Register", "Rd <- Rd | K",
        u("Sets the bits that are 1 in K. Same as ORI, so Rd must be R16-R31.",
          "sbr r16, (1<<2)  ; set bit 2")),
];

/// Looks up an alias by lower-case name.
pub fn alias(name: &str) -> Option<&'static Alias> {
    ALIASES.iter().find(|a| a.name == name)
}

#[cfg(test)]
mod tests {
    #[test]
    fn every_instruction_has_usage() {
        for def in super::super::isa::insns() {
            assert!(super::insn_usage(def.name).is_some(), "missing usage help for {}", def.name);
        }
    }
    #[test]
    fn aliases_point_at_real_instructions() {
        for a in super::ALIASES {
            assert!(super::super::isa_docs::insn_doc(a.of).is_some(), "{} -> {}", a.name, a.of);
            assert!(super::super::isa_docs::insn_doc(a.name).is_none(), "{} is canonical", a.name);
        }
    }
}
