#!/usr/bin/env python3
"""Assembles programs/*.s for riscv32imc and writes programs.rs (checked in, so the tests do not
need a toolchain).

Usage: python3 gen_programs.py [out.rs]

Needs a Rust toolchain with the `riscv32imc-unknown-none-elf` target: rustc assembles the
`.s` text through `core::arch::global_asm!` and links it at 0x4200_0000 (the ESP32-C3 IROM window);
`llvm-objcopy` / `llvm-nm` from the toolchain's `llvm-tools` extract the image and the symbols.
Every program is prefixed with `programs/common.inc`.
"""
import glob
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
PROGS = os.path.join(HERE, "programs")
BASE = 0x42000000
SYSROOT = subprocess.check_output(["rustc", "--print", "sysroot"]).decode().strip()
HOST = subprocess.check_output(["rustc", "-vV"]).decode().split("host: ")[1].split()[0]
TOOLS = os.path.join(SYSROOT, "lib", "rustlib", HOST, "bin")


def build(name):
    with open(os.path.join(PROGS, "common.inc")) as f:
        common = f.read()
    with open(os.path.join(PROGS, name + ".s")) as f:
        body = f.read()
    src = '#![no_std]\n#![no_main]\n#[panic_handler] fn p(_: &core::panic::PanicInfo) -> ! { loop {} }\n'
    src += 'core::arch::global_asm!(r#"\n' + common + "\n" + body + '\n"#);\n'
    with tempfile.TemporaryDirectory() as tmp:
        rs = os.path.join(tmp, "t.rs")
        elf = os.path.join(tmp, "t.elf")
        binf = os.path.join(tmp, "t.bin")
        with open(rs, "w") as f:
            f.write(src)
        r = subprocess.run(
            ["rustc", "--target", "riscv32imc-unknown-none-elf", "-C", "panic=abort", f"-Clink-arg=-Ttext=0x{BASE:x}", "-O", rs, "-o", elf],
            capture_output=True,
            text=True,
        )
        if r.returncode:
            sys.exit(f"{name}.s failed to assemble:\n{r.stderr[:3000]}")
        subprocess.check_call([os.path.join(TOOLS, "llvm-objcopy"), "-O", "binary", "--only-section=.text", elf, binf])
        nm = subprocess.check_output([os.path.join(TOOLS, "llvm-nm"), "--defined-only", elf]).decode()
        with open(binf, "rb") as f:
            code = f.read()
    syms = []
    for line in nm.splitlines():
        m = re.match(r"^([0-9a-f]+) [tTdD] (\w+)$", line)
        if m and not m.group(2).startswith("__"):
            syms.append((m.group(2), int(m.group(1), 16) - BASE))
    syms.sort(key=lambda s: s[1])
    return code, syms


def main():
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "programs.rs")
    names = sorted(os.path.basename(p)[:-2] for p in glob.glob(os.path.join(PROGS, "*.s")))
    with open(out, "w") as f:
        f.write("// @generated by gen_programs.py (rustc riscv32imc) from programs/*.s; do not edit by hand.\n")
        f.write("#![allow(dead_code)]\n\n")
        f.write(
            "/// An assembled test program: bytes for the IROM start (0x4200_0000) and symbols (offsets).\n"
            "pub struct Prog {\n    pub code: &'static [u8],\n    pub syms: &'static [(&'static str, u32)],\n}\n\n"
            "impl Prog {\n    /// Absolute address of a symbol.\n    pub fn sym(&self, name: &str) -> u32 {\n"
            '        0x4200_0000 + self.syms.iter().find(|s| s.0 == name).unwrap_or_else(|| panic!("symbol {name}")).1\n    }\n}\n\n'
        )
        for n in names:
            code, syms = build(n)
            bs = ", ".join(f"0x{b:02x}" for b in code)
            ss = ", ".join(f'("{s}", 0x{o:x})' for s, o in syms)
            f.write(f"pub const {n.upper()}: Prog = Prog {{\n    code: &[{bs}],\n    syms: &[{ss}],\n}};\n\n")
            print(n, len(code), "bytes", len(syms), "symbols")


if __name__ == "__main__":
    main()
