#!/usr/bin/env python3
"""Assembles programs/*.s with Apple clang (thumbv7em) and writes programs.rs.

Usage: python3 gen_programs.py [out.rs]   (run from anywhere; needs Xcode command line tools)
The generated file is checked in, so the tests do not need clang.
"""
import os
import re
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
PROGS = os.path.join(HERE, "programs")
OBJDUMP = subprocess.check_output(["xcrun", "--find", "llvm-objdump"]).decode().strip()


def assemble(src):
    with tempfile.TemporaryDirectory() as tmp:
        obj = os.path.join(tmp, "a.o")
        subprocess.check_call(
            ["clang", "--target=thumbv7em-none-eabi", "-mcpu=cortex-m4", "-I", PROGS, "-c", src, "-o", obj]
        )
        dump = subprocess.check_output([OBJDUMP, "-s", "-j", ".text", obj]).decode()
        syms = subprocess.check_output([OBJDUMP, "-t", obj]).decode()
    data = bytearray()
    for line in dump.splitlines():
        m = re.match(r"^ ([0-9a-f]{4}) ((?:[0-9a-f]+ ?)+)", line)
        if m:
            off = int(m.group(1), 16)
            hexs = m.group(2).replace(" ", "")
            # llvm-objdump pads the ASCII column after two spaces; keep the hex part only.
            chunk = bytes.fromhex(hexs[: len(hexs) - len(hexs) % 2])
            assert off == len(data) or off + len(chunk) >= len(data)
            data[off : off + len(chunk)] = chunk
    out = []
    for line in syms.splitlines():
        m = re.match(r"^([0-9a-f]{8}) g\s+(?:F\s+)?\.text\s+[0-9a-f]{8} (\S+)$", line)
        if m:
            out.append((m.group(2), int(m.group(1), 16) & ~1))
    return bytes(data), out


def main():
    out_path = sys.argv[1] if len(sys.argv) > 1 else os.path.join(HERE, "programs.rs")
    lines = [
        "// @generated by gen_programs.py (Apple clang, thumbv7em) from programs/*.s; do not edit by hand.",
        "#![allow(dead_code)]",
        "",
        "/// An assembled test program: bytes for the flash start and global symbols (flash offsets).",
        "pub struct Prog {",
        "    pub code: &'static [u8],",
        "    pub syms: &'static [(&'static str, u32)],",
        "}",
        "",
        "impl Prog {",
        "    /// Absolute address (flash base 0x0800_0000) of a global symbol.",
        "    pub fn sym(&self, name: &str) -> u32 {",
        "        0x0800_0000 + self.syms.iter().find(|s| s.0 == name).unwrap_or_else(|| panic!(\"symbol {name}\")).1",
        "    }",
        "}",
        "",
    ]
    for fn in sorted(os.listdir(PROGS)):
        if not fn.endswith(".s"):
            continue
        code, syms = assemble(os.path.join(PROGS, fn))
        name = fn[:-2].upper()
        body = ", ".join("0x%02x" % b for b in code)
        lines.append("pub const %s: Prog = Prog {" % name)
        lines.append("    code: &[%s]," % body)
        lines.append("    syms: &[%s]," % ", ".join('("%s", 0x%x)' % s for s in syms))
        lines.append("};")
        lines.append("")
    with open(out_path, "w") as f:
        f.write("\n".join(lines))


main()
