#!/usr/bin/env python3
"""Generates esp32c3_gen.rs: register templates, peripheral base addresses and interrupt source numbers.

Usage: gen_esp32c3.py <esp32c3.svd> [out.rs]

The SVD is Espressif's official one (https://github.com/espressif/svd, Apache-2.0); it is NOT checked in,
only the generated Rust file is. Register offsets, field masks, names, descriptions and reset values come from
the SVD. Peripheral instances that are `derivedFrom` another one (UART1, TIMG1) share the template of the first.
`dim`/`%s` register arrays are expanded (GPIO%s -> GPIO0 .. GPIO21).
"""
import os
import re
import sys
import xml.etree.ElementTree as ET

SRC = sys.argv[1]
OUT = sys.argv[2] if len(sys.argv) > 2 else os.path.join(os.path.dirname(os.path.abspath(__file__)), "esp32c3_gen.rs")

# (template name, SVD peripheral it is taken from)
TEMPLATES = [
    ("SYSTEM", "SYSTEM"),
    ("INTERRUPT_CORE0", "INTERRUPT_CORE0"),
    ("SYSTIMER", "SYSTIMER"),
    ("TIMG", "TIMG0"),
    ("RTC_CNTL", "RTC_CNTL"),
    ("GPIO", "GPIO"),
    ("IO_MUX", "IO_MUX"),
    ("UART", "UART0"),
    ("USB_DEVICE", "USB_DEVICE"),
]
# instances whose base address is exported (name -> SVD peripheral)
INSTANCES = ["SYSTEM", "INTERRUPT_CORE0", "SYSTIMER", "TIMG0", "TIMG1", "RTC_CNTL", "GPIO", "IO_MUX", "UART0", "UART1", "USB_DEVICE"]

root = ET.parse(SRC).getroot()
periph = {p.findtext("name"): p for p in root.iter("peripheral")}
default_reset = int(root.findtext("resetValue") or "0", 0)


def num(text, default=0):
    return int(text, 0) if text else default


def text(e, tag):
    t = e.findtext(tag) if e is not None else None
    return re.sub(r"\s+", " ", t).strip() if t else ""


def rs(s, limit=110):
    s = s.replace("\\", "\\\\").replace('"', '\\"')
    return s if len(s) <= limit else s[: limit - 1].rstrip() + "..."


def indices(reg):
    dim = reg.findtext("dim")
    if dim is None:
        return None
    idx = reg.findtext("dimIndex")
    if idx:
        m = re.fullmatch(r"(\d+)-(\d+)", idx)
        if m:
            return [str(i) for i in range(int(m.group(1)), int(m.group(2)) + 1)]
        return [s.strip() for s in idx.split(",")]
    return [str(i) for i in range(int(dim, 0))]


def registers(p):
    out = []
    node = p.find("registers")
    for r in list(node) if node is not None else []:
        if r.tag != "register":
            raise SystemExit("unexpected %s in %s" % (r.tag, p.findtext("name")))
        base_off = num(r.findtext("addressOffset"))
        reset = num(r.findtext("resetValue"), default_reset)
        fields = []
        accs = set()
        for f in (r.find("fields") if r.find("fields") is not None else []):
            off, w = num(f.findtext("bitOffset")), num(f.findtext("bitWidth"), 1)
            fields.append((f.findtext("name"), ((1 << w) - 1) << off, text(f, "description")))
            accs.add(f.findtext("access") or "read-write")
        if accs == {"read-only"}:
            acc = "r"
        elif accs == {"write-only"}:
            acc = "w"
        else:
            acc = "rw"
        names = r.findtext("name")
        idx = indices(r)
        step = num(r.findtext("dimIncrement"))
        if idx is None:
            out.append((names, base_off, reset, acc, text(r, "description"), fields))
        else:
            for k, i in enumerate(idx):
                out.append((names.replace("%s", i), base_off + k * step, reset, acc, text(r, "description"), fields))
    out.sort(key=lambda x: x[1])
    return out


lines = [
    "// @generated by gen_esp32c3.py from Espressif's esp32c3.svd (Apache-2.0, https://github.com/espressif/svd): register",
    "// layout, bit fields, reset values and interrupt source numbers; do not edit by hand.",
    "#![allow(clippy::all)]",
    "",
    "pub use super::gen_types::{BitDef, RegDef};",
    "",
    "/// Base address of every modelled peripheral instance.",
    "pub const BASES: &[(&str, u32)] = &[",
]
for n in INSTANCES:
    lines.append('    ("%s", 0x%08x),' % (n, num(periph[n].findtext("baseAddress"))))
lines.append("];")
lines.append("")

for tname, pname in TEMPLATES:
    lines.append("pub const %s: &[RegDef] = &[" % tname)
    for name, off, reset, acc, desc, fields in registers(periph[pname]):
        bits = ", ".join('BitDef { name: "%s", mask: 0x%08x, desc: "%s" }' % (fn, m, rs(fd, 60)) for fn, m, fd in fields)
        lines.append('    RegDef { name: "%s", off: 0x%x, reset: 0x%08x, access: "%s", desc: "%s", bits: &[%s] },' % (name, off, reset, acc, rs(desc), bits))
    lines.append("];")
    lines.append("")

# Peripheral interrupt sources of the interrupt matrix: (name, source number).
srcs = {}
for p in root.iter("peripheral"):
    for i in p.findall("interrupt"):
        srcs[int(i.findtext("value"))] = i.findtext("name")
lines.append("/// Interrupt matrix peripheral sources `(name, source number)`, sorted by number. Source n is mapped to a CPU")
lines.append("/// interrupt by the INTERRUPT_CORE0 register at offset 4 * n.")
lines.append("pub const INTR_SOURCES: &[(&str, u8)] = &[")
for v in sorted(srcs):
    lines.append('    ("%s", %d),' % (srcs[v], v))
lines.append("];")
lines.append("")

with open(OUT, "w") as f:
    f.write("\n".join(lines))
print("wrote", OUT, len(lines), "lines")
